version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./database.sqlite:/app/database.sqlite
    environment:
      - NODE_ENV=development
    command: npm run start:dev